### ISSUE TITLE
Bid Crash

### ISSUE THREAD

**Issue by nglabs42** [RunDavidMC/Namebase-Extended#3]
Running 7000 names, was doing 1 second between each request got the following.  I assume this is because too many request?

I have included the other errors I am getting while bidding if I need to move them to individual issues let me know.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user1/repos/Namebase-Extended/main.py", line 115, in <module>
    menu()
  File "/Users/user1/repos/Namebase-Extended/main.py", line 87, in menu
    handler(choice)
  File "/Users/user1/repos/Namebase-Extended/main.py", line 91, in handler
    bid.main(cookie)
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 218, in main
    menu()
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 174, in menu
    handler(choice)
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 203, in handler
    multiName()
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 197, in multiName
    bidder(names)
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 141, in bidder
    req()
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 100, in req
    r = requests.post(endpoint + "/api/v0/auction/" + x + "/bid", params=params, data=json.dumps(params), headers=headers, cookies={"namebase-main": cookies}).json()
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**Comment by nglabs42** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user1/repos/Namebase-Extended/main.py", line 115, in <module>
    menu()
  File "/Users/user1/repos/Namebase-Extended/main.py", line 87, in menu
    handler(choice)
  File "/Users/user1/repos/Namebase-Extended/main.py", line 91, in handler
    bid.main(cookie)
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 218, in main
    menu()
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 174, in menu
    handler(choice)
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 203, in handler
    multiName()
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 197, in multiName
    bidder(names)
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 141, in bidder
    req()
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 100, in req
    r = requests.post(endpoint + "/api/v0/auction/" + x + "/bid", params=params, data=json.dumps(params), headers=headers, cookies={"namebase-main": cookies}).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
: 0

**Comment by nglabs42** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user1/repos/Namebase-Extended/main.py", line 115, in <module>
    menu()
  File "/Users/user1/repos/Namebase-Extended/main.py", line 87, in menu
    handler(choice)
  File "/Users/user1/repos/Namebase-Extended/main.py", line 91, in handler
    bid.main(cookie)
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 218, in main
    menu()
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 174, in menu
    handler(choice)
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 203, in handler
    multiName()
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 197, in multiName
    bidder(names)
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 141, in bidder
    req()
  File "/Users/user1/repos/Namebase-Extended/bid.py", line 100, in req
    r = requests.post(endpoint + "/api/v0/auction/" + x + "/bid", params=params, data=json.dumps(params), headers=headers, cookies={"namebase-main": cookies}).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
